name: deploy

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  deploy:
    # this will run when you have tagged a commit
    runs-on: ubuntu-latest
    if: contains(github.ref, 'tags')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -U "flit>=3.2,<4"
      - name: Build and publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          git tag
          flit publish